# Generated by Django 4.2.2 on 2023-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="My Data Science Blog", max_length=255),
        ),
    ]
