# Generated by Django 4.2.2 on 2023-07-01 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateField(
                auto_created=True, default=datetime.date(2023, 7, 1)
            ),
        ),
    ]
