# Generated by Django 4.2.2 on 2023-07-01 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0004_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
    ]
