# Generated by Django 4.2.2 on 2023-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0005_alter_post_post_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="Blog Topics", max_length=255),
        ),
    ]
