# Generated by Django 4.2.2 on 2023-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0006_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="BlogTopics", max_length=255),
        ),
    ]
